apiVersion: apps/v1
kind: Deployment
metadata:
  name: sports-nexus-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sports-nexus
  template:
    metadata:
      labels:
        app: sports-nexus
    spec:
      containers:
        - name: app
          image: 834922934378.dkr.ecr.ap-south-1.amazonaws.com/sports-nexus:40
          ports:
            - containerPort: 8080
